# Generated by Django 3.0 on 2020-11-07 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drzavljanstvo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=192)),
            ],
        ),
        migrations.CreateModel(
            name='KlasifikacijaNesrece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=192)),
            ],
        ),
        migrations.CreateModel(
            name='Lokacija',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=192)),
            ],
        ),
        migrations.CreateModel(
            name='Nesreca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zaporedna_stevilka', models.CharField(blank=True, max_length=64, null=True)),
                ('datum', models.DateField(blank=True, null=True)),
                ('ura', models.TimeField(blank=True, null=True)),
                ('v_naselju', models.BooleanField(blank=True, null=True)),
                ('geo_x', models.FloatField(blank=True, null=True)),
                ('geo_y', models.FloatField(blank=True, null=True)),
                ('klasifikacija', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pasovcek.KlasifikacijaNesrece')),
                ('lokacija', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pasovcek.Lokacija')),
            ],
        ),
        migrations.CreateModel(
            name='SifraCeste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=192)),
            ],
        ),
        migrations.CreateModel(
            name='SifraOdsekaUlice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=192)),
            ],
        ),
        migrations.CreateModel(
            name='StanjePrometa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=192)),
            ],
        ),
        migrations.CreateModel(
            name='StanjeVozisca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=192)),
            ],
        ),
        migrations.CreateModel(
            name='TipNesrece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=192)),
            ],
        ),
        migrations.CreateModel(
            name='TipPoskodbe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=192)),
            ],
        ),
        migrations.CreateModel(
            name='UEStalnegaPrebivalisca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=192)),
            ],
        ),
        migrations.CreateModel(
            name='UpravnaEnotaStoritve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=192)),
            ],
        ),
        migrations.CreateModel(
            name='VremenskeOkoliscine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=192)),
            ],
        ),
        migrations.CreateModel(
            name='VrstaCeste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=192)),
            ],
        ),
        migrations.CreateModel(
            name='VrstaPrometa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=192)),
            ],
        ),
        migrations.CreateModel(
            name='VrstaUdelezenca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=192)),
            ],
        ),
        migrations.CreateModel(
            name='VrstaVozisca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=192)),
            ],
        ),
        migrations.CreateModel(
            name='VzrokNesrece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=192)),
            ],
        ),
        migrations.CreateModel(
            name='Oseba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zaporedna_stevilka', models.CharField(blank=True, max_length=64, null=True)),
                ('vpn_stevilka', models.IntegerField(blank=True, null=True)),
                ('je_povzrocitelj', models.BooleanField(blank=True, null=True)),
                ('starost', models.IntegerField(blank=True, null=True)),
                ('spol', models.IntegerField(blank=True, choices=[(0, 'Moški'), (1, 'Ženska')], null=True)),
                ('vozniski_staz', models.FloatField(blank=True, null=True)),
                ('uporaba_pasu', models.BooleanField(blank=True, null=True)),
                ('vrednost_alkotesta', models.FloatField(blank=True, null=True)),
                ('strokovni_pregled', models.FloatField(blank=True, null=True)),
                ('drzavljanstvo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pasovcek.Drzavljanstvo')),
                ('nesreca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='udelezenci', to='pasovcek.Nesreca')),
                ('poskodba', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pasovcek.TipPoskodbe')),
                ('use_prebivalisca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pasovcek.UpravnaEnotaStoritve')),
                ('vrsta_udelezenca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pasovcek.VrstaUdelezenca')),
            ],
        ),
        migrations.AddField(
            model_name='nesreca',
            name='sifra_ceste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pasovcek.SifraCeste'),
        ),
        migrations.AddField(
            model_name='nesreca',
            name='sifra_odseka_ulice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pasovcek.SifraOdsekaUlice'),
        ),
        migrations.AddField(
            model_name='nesreca',
            name='stanje_prometa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pasovcek.StanjePrometa'),
        ),
        migrations.AddField(
            model_name='nesreca',
            name='stanje_vozisca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pasovcek.StanjeVozisca'),
        ),
        migrations.AddField(
            model_name='nesreca',
            name='tip_nesrece',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pasovcek.TipNesrece'),
        ),
        migrations.AddField(
            model_name='nesreca',
            name='vremenske_okoliscine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pasovcek.VremenskeOkoliscine'),
        ),
        migrations.AddField(
            model_name='nesreca',
            name='vrsta_ceste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pasovcek.VrstaCeste'),
        ),
        migrations.AddField(
            model_name='nesreca',
            name='vrsta_vozisca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pasovcek.VrstaVozisca'),
        ),
        migrations.AddField(
            model_name='nesreca',
            name='vzrok_nesrece',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pasovcek.VzrokNesrece'),
        ),
    ]
