# Generated by Django 3.1.3 on 2020-11-07 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pasovcek', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UEStalnegaPrebivalisca',
        ),
    ]
