# Generated by Django 3.1.3 on 2020-11-07 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pasovcek', '0002_delete_uestalnegaprebivalisca'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpisKraja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=192)),
            ],
        ),
        migrations.CreateModel(
            name='StacionazaDogodka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=192)),
            ],
        ),
        migrations.CreateModel(
            name='TextCesteNaselja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=192)),
            ],
        ),
        migrations.CreateModel(
            name='TextOdsekaUlice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=192)),
            ],
        ),
        migrations.RemoveField(
            model_name='oseba',
            name='use_prebivalisca',
        ),
        migrations.AddField(
            model_name='nesreca',
            name='ue_storitve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pasovcek.upravnaenotastoritve'),
        ),
        migrations.AddField(
            model_name='oseba',
            name='ue_prebivalisca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pasovcek.upravnaenotastoritve'),
        ),
        migrations.AddField(
            model_name='nesreca',
            name='opis_kraja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pasovcek.opiskraja'),
        ),
        migrations.AddField(
            model_name='nesreca',
            name='stacionaza_dogodka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pasovcek.stacionazadogodka'),
        ),
        migrations.AddField(
            model_name='nesreca',
            name='text_ceste_naselja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pasovcek.textcestenaselja'),
        ),
        migrations.AddField(
            model_name='nesreca',
            name='text_odseka_ulice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pasovcek.textodsekaulice'),
        ),
    ]
